export const blackList: any = {
  'USDT-BADGER': ['Kucoin'],
  'USDT-FTM3L': ['Kucoin'],
  'USDT-FTM3S': ['Kucoin'],
  'USDT-LTC3L': ['Kucoin'],
  'USDT-LTC3S': ['Kucoin'],
  'USDT-JASMY3L': ['Kucoin'],
  'USDT-JASMY3S': ['Kucoin'],
  'USDT-NEAR3L': ['Kucoin'],
  'USDT-NEAR3S': ['Kucoin'],
  'USDT-AVAX3L': ['Kucoin'],
  'USDT-AVAX3S': ['Kucoin'],
  'USDT-EOS3L': ['Kucoin'],
  'USDT-EOS3S': ['Kucoin'],
  'USDT-DOT3L': ['Kucoin'],
  'USDT-DOT3S': ['Kucoin'],
  'USDT-UNI3L': ['Kucoin'],
  'USDT-UNI3S': ['Kucoin'],
  'USDT-VET3L': ['Kucoin'],
  'USDT-VET3S': ['Kucoin'],
  'USDT-ETH3L': ['Kucoin'],
  'USDT-ETH3S': ['Kucoin'],
  'USDT-LINK3L': ['Kucoin'],
  'USDT-LINK3S': ['Kucoin'],

  'USDT-MC': ['Kucoin'],
  'USDT-MOOV': ['Kucoin'],
  'USDT-ACA': ['Kucoin'],
  'USDT-QI': ['Kucoin', 'Mexc', 'Binance'],
  'USDT-JAM': ['Kucoin', 'Mexc'],
  'USDT-GMT': ['Exmo', 'Mexc', 'Coinbase'],
  'USDT-DC': ['Huobi'],
  'USDT-RUNE': ['Bybit'],
  'USDT-SOUL': ['Mexc', 'Kucoin'],
  'USDT-PIT': ['Okx', 'Mexc'],
  'USDT-BRISE': ['Kucoin', 'Mexc'],
  'USDT-HOTCROSS': ['Mexc'],
  'USDT-IOTA': ['Kucoin'],
}
